sudo: false
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- wget --no-clobber https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz
- tar -xvf hugo_0.18.1_Linux-64bit.tar.gz
- ln -s $PWD/hugo_0.18.1_linux_amd64/hugo_0.18.1_linux_amd64 $PWD/hugo_0.18.1_linux_amd64/hugo
- export PATH=$PATH:$PWD/hugo_0.18.1_linux_amd64/
script: bash ./scripts/build-all-deploy-non-master.sh
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: www.lixor.se
  skip_cleanup: true
  region: eu-central-1
  local_dir: public
  on:
    branch: master
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
env:
  global:
  - ENCRYPTION_LABEL: a46ce31c1990
  - CLOUDFRONT_DISTRIBUTION_ID: E262ZG7MIQ9Y64
  - AWS_ACCESS_KEY_ID: AKIAJHZHH4VEWM647INA
  - secure: CexHtOH3xmQ/vQ34YDnX1pVxRBDXsQ/a8Pp8+iaVjD1MfsQXWFQp8i34h0rnk/XefeC9MRs0huvU38lkuv508O97x4DxIujJIokLg2EGWF9gB4fYeQtXBfiV6ePHDJfFvpcUaaGI4OXYKg+fuiUtIp/r5PL0788CUam4y7fkkj2uMBXsJN+iWFxWDQL9vVuglxhVoRKdWkLxWu5TO8L7NMnka7olAVSLIR23FTCpuIJEPee47qxE/etxZwQmFq70xVlesmI2h4/D+tZ0IbZVGq4n1UpRgSOPziXUdkgf1/a47LPAXeE6N1HXUan39iE/tuFMCSkSdKKNVBRA4j3+MPhvfhXttuHqojH2LlLNOgNO1d0ZXSQsXkBTLd9190ycmP7qrMPhqpqKgzaBkHvuxbzJgBHWgwN1CdcdoVPAYYd20uDRzw3oFOtbrK/m5xQ9bxb55/o1n9+j09GefpRaWyAS0+EmAWhJXSNQj5sne0R8jQpnUUqOCNBsoU2mSte21jobFNQtNvrvC+nOftzA+krnzpFfRcSAS6B7q7Q2b2omUwtELMA9eujmfeFGftw/aq4CirTPPI1WSIexHRDtkeqedTxkHrCCMj1MXgvUFDjvynjvKIAz26/GQZdt244B4kg6HUTY/ckDyXObS2CUNipFVah6/D+umc4QG3kxseY=
language: node_js
node_js:
- stable
cache: yarn
branches:
  except:
  - gh-pages
notifications:
  slack:
    template:
    - |
      https://www.lixor.se (master branch) or https://lixor-ab.github.io/ (anything else) update by %{author} %{result}
    - |
      Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} in %{duration}
    - '"%{commit_subject}"'
    rooms:
      secure: ayWRh1c8PWAUQe4WGxC9PI//7h8sBeKC8teb5f4JrFBfP6UT9NA8lYB0wlVeH/K736FyKPQxY4KDNbrbodmn6BUf7eVZdYHk+pdE5sqk4ZtrYg+oIwy8EJ96sM/KuO5jTJpE0/wdLg77Wepykbk9HR0BwIKjVPGe/xRW0SodrTd1gADkw7f+ts3o/gdeDvnkwX5r/6RQ0HtgQmxWRYrSGUlrqNkmLqPCW4n9dRxzwQIzFQHgKky8aYhpGascrWl26yJNUS5M0uVojytQZDq/d/SGqnID1hV5WT9P4I/ijpxWXxglJOz/KyZUBB6GaixxDUNAfbjP3hNJiI5p9g3W7L9n2KvsUn/k4lxRz46gJlirG4lB9kpX4ngc+fyj0xhCVmAaMf09zUQKewYH1yRzh99MxYbh0eZk/yfghsYATBCnqyc3WcvBXVHZF+jqL1+J/XwSYbDiDPYPcn7LAXQm+/lV71PKm1o67qE6VYcYr8dpHMEAr8SOIn/1pAv3h4ipPSiJfWMreh3QrapPttOaePkCKOB8sfwDac/8UMwwWuaJzAZA8KJZO6M5TrZNoRfV5p1ipf19oGpXwTwJKmflgm6/uKagDtlqfmnlxQJdKwfGwd5vk8YO+lk3MVSvu0rpk0ABnhrGtjlSxSepxxxu++tORW2+0JLf1ZB8ZWgR/aA=
