before_install:
- wget https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1-64bit.deb
- sudo dpkg -i hugo_0.18.1-64bit.deb
script: bash ./scripts/deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: a46ce31c1990
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
notifications:
  slack:
    rooms:
      secure: ayWRh1c8PWAUQe4WGxC9PI//7h8sBeKC8teb5f4JrFBfP6UT9NA8lYB0wlVeH/K736FyKPQxY4KDNbrbodmn6BUf7eVZdYHk+pdE5sqk4ZtrYg+oIwy8EJ96sM/KuO5jTJpE0/wdLg77Wepykbk9HR0BwIKjVPGe/xRW0SodrTd1gADkw7f+ts3o/gdeDvnkwX5r/6RQ0HtgQmxWRYrSGUlrqNkmLqPCW4n9dRxzwQIzFQHgKky8aYhpGascrWl26yJNUS5M0uVojytQZDq/d/SGqnID1hV5WT9P4I/ijpxWXxglJOz/KyZUBB6GaixxDUNAfbjP3hNJiI5p9g3W7L9n2KvsUn/k4lxRz46gJlirG4lB9kpX4ngc+fyj0xhCVmAaMf09zUQKewYH1yRzh99MxYbh0eZk/yfghsYATBCnqyc3WcvBXVHZF+jqL1+J/XwSYbDiDPYPcn7LAXQm+/lV71PKm1o67qE6VYcYr8dpHMEAr8SOIn/1pAv3h4ipPSiJfWMreh3QrapPttOaePkCKOB8sfwDac/8UMwwWuaJzAZA8KJZO6M5TrZNoRfV5p1ipf19oGpXwTwJKmflgm6/uKagDtlqfmnlxQJdKwfGwd5vk8YO+lk3MVSvu0rpk0ABnhrGtjlSxSepxxxu++tORW2+0JLf1ZB8ZWgR/aA=

